### ISSUE TITLE
Just want to share my solution

### ISSUE THREAD

**Issue by qoomon** [antonmedv/spark#10]
https://github.com/qoomon/starline

- It supports repos, gists, and users.
- It bypasses the rate limit by using GITHUB_TOKEN opf github actions, even facebook/react with over 200k stargazers can be fetched within an hour.
- No "server" needed. Image serving and trigger image job is done by an simple vercel function. Caching stargazers and images are implemented by utilizing GitHub release assets.

Best regards and thanks so much for this project it was a great inspiration to hack an serverless variation of yours.

**Comment by antonmedv** [comment]
Lets add this as a like to readme?

**Comment by antonmedv** [comment]
Done: https://github.com/antonmedv/spark/blob/master/README.md
