### ISSUE TITLE
[Feature Request] User based graph

### ISSUE THREAD

**Issue by qoomon** [antonmedv/spark#4]
Would be nice to have a graph for all stars of an user or organization.
e.g. `https://stars.medv.io/facebook`

**Comment by antonmedv** [comment]
Can you write a PR for this? :)

**Comment by qoomon** [comment]
Sorry I don't have time for that. 

Anyways thanks a lot for this awesome visualisation service

**Comment by qoomon** [comment]
GraphQL Query to get all gists and repositories => https://github.com/antonmedv/spark/pull/6#issuecomment-1931594686

**Comment by antonmedv** [comment]
We can same list of user repos to a file: `db.json` and use it later.

**Comment by qoomon** [comment]
I'll close this cause it works on my solution already https://github.com/qoomon/starlines
