### ISSUE TITLE
[Feature Request]  Support GitHub Gists

### ISSUE THREAD

**Issue by qoomon** [antonmedv/spark#5]
Would be nice if this project add support for GitHub Gist as well e.g. https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13

**Comment by antonmedv** [comment]
Wow. This is a lot of stars on a gist. Nice work! =) I will think of adding a such feature. 

BTW, I think I should create a separate badge for a lot of stars on a gist (my other project https://github.com/my-badges/my-badges)

**Comment by qoomon** [comment]
Here is the graphQL query to query all gist stars
```graphql
query($name: String!, $endCursor: String) {
  viewer {
    gist(name: $name) {
      stargazers(first: 100, after: $endCursor) {
        totalCount
        edges {
          starredAt
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
  rateLimit {
    remaining
  }
}
```
